### ISSUE TITLE
when running main.py I call a function in lebanese_to_roman.py which calls another function in dictionaries.py that returns new value from a dictionary but error occurs.

### ISSUE THREAD

**Issue by nathanbowley98** [nathanbowley98/lebanese_app#1]
error code: 

C:\Users\natha\PycharmProjects\translator\venv\Scripts\python.exe C:/Users/natha/PycharmProjects/translator/venv/main.py
C:\Users\natha\PycharmProjects\translator\venv\lib\site-packages\pydub\utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
C:\Users\natha\PycharmProjects\translator\venv\lib\site-packages\pydub\utils.py:179: RuntimeWarning: Couldn't find ffplay or avplay - defaulting to ffplay, but may not work
  warn("Couldn't find ffplay or avplay - defaulting to ffplay, but may not work", RuntimeWarning)
Input arabic word here to have it converted: دَرْس
دَرْس
**Traceback (most recent call last):
  File "C:/Users/natha/PycharmProjects/translator/venv/main.py", line 20, in <module>
    main()
  File "C:/Users/natha/PycharmProjects/translator/venv/main.py", line 18, in main
    lebanese_to_roman.arabic_to_roman_replace(test_word)
  File "C:\Users\natha\PycharmProjects\translator\lebanese\lebanese_to_roman.py", line 27, in arabic_to_roman_replace
    if letter in Dictionary.lebanese_dictionary(letter):
TypeError: lebanese_dictionary() missing 1 required positional argument: 'letter'**
 |1|  د |2|  َ |3|  ر |4|  ْ |5|  س 

Process finished with exit code 1

**Comment by theunkn0wn1** [comment]
caused by https://github.com/nathanbowley98/lebanese_app/blob/master/lebanese/dictionaries.py#L7

You define this routine to be a `@staticmethod` yet define it to accept a `self` argument.

Static methods do not accept a self argument, and this is the source of your above exception.
